task: fever10
dataset_path: fever
dataset_name: v1.0
output_type: multiple_choice
training_split: train
validation_split: labelled_dev
test_split: null
doc_to_text: "Claim: {{claim}}\nLabel:"
doc_to_choice: ["SUPPORTS", "REFUTES", "NOT ENOUGH INFO"]
doc_to_target: label
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 0.0
