task: nq_swap
dataset_path: pminervini/NQ-Swap
output_type: generate_until
validation_split: substituted
description: "Answer the following question based on the provided context:\n\n"
doc_to_text: "Context: {{context}}\nQuestion: {{question}}?\nAnswer:"
doc_to_target: "{{answer}}" # TODO: should be multi-target
fewshot_delimiter: "\n\n"
generation_kwargs:
  until:
    - "\n"
    - "."
    - ","
  do_sample: false
  temperature: 0.0
filter_list:
  - name: remove_whitespace
    filter:
      - function: remove_whitespace
      - function: take_first
target_delimiter: " "
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
    regexes_to_ignore:
    - "\\b(?:The |the |An |A |The |a |an )"
metadata:
  version: 0.0