task: faithdial_hallu_v2
dataset_path: McGill-NLP/FaithDial
training_split: train
validation_split: validation
test_split: test
output_type: multiple_choice
doc_to_text: !function utils.doc_to_text_v2
doc_to_target: !function utils.doc_to_target
doc_to_choice: ["false", "true"]
metric_list:
  - metric: acc
    higher_is_better: True
metadata:
  version: 0.0
